---
# Post tasks

- name: Perform DNF package cleanup
  dnf:
      autoremove: yes
  changed_when: no

- name: flush handlers
  meta: flush_handlers

- name: Reboot host
  reboot:
  when:
  - not skip_reboot
