---
# Post tasks

- name: Perform DNF package cleanup
  dnf:
      autoremove: yes
  changed_when: no
  ignore_errors: yes

- name: flush handlers
  meta: flush_handlers

- name: Reboot host
  reboot:
  when:
  - not rhel8cis_skip_reboot
