---
# Post tasks

- name: Perform DNF package cleanup
  dnf:
      autoremove: yes
  changed_when: no

- name: flush handlers
  meta: flush_handlers

- name: reboot system if changes require it and not skipped
  block:
      - name: Reboot system if changes require it and not skipped
        reboot:
        when:
            - change_requires_reboot
            - not skip_reboot

      - name: Warning a reboot required but skip option set
        debug:
            msg: "Warning!! changes have been made that require a reboot to be implemented but skip reboot was set - Can affect compliance check results"
        changed_when: true
        when:
            - change_requires_reboot
            - skip_reboot
  tags:
      - grub
      - rhel8cis_section1
      - rhel8cis_section2
      - rhel8cis_section3
      - rhel8cis_section4
      - rhel8cis_section5
      - rhel8cis_section6
