---

- name: "1.5.1 | PATCH | Ensure core dump storage is disabled"
  lineinfile:
      path: /etc/systemd/coredump.conf
      regexp: 'Storage='
      line: 'Storage=none'
  notify: systemd_daemon_reload
  when:
      - rhel8cis_rule_1_5_1
      - systemd_coredump.stat.exists
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_1.5.1

- name: "1.5.2 | PATCH | Ensure core dump backtraces are disabled"
  lineinfile:
      path: /etc/systemd/coredump.conf
      regexp: 'ProcessSizeMax='
      line: 'ProcessSizeMax=0'
  when:
      - rhel8cis_rule_1_5_2
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - sysctl
      - rule_1.5.2

- name: "1.5.3 | PATCH | Ensure address space layout randomization (ASLR) is enabled"
  sysctl:
      name: kernel.randomize_va_space
      value: '2'
      state: present
      reload: yes
      sysctl_set: yes
      ignoreerrors: yes
  when:
      - rhel8cis_rule_1_5_3
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - sysctl
      - rule_1.5.3

# - name: "1.6.1 | L1 | PATCH | Ensure core dumps are restricted"
#   block:
#       - name: "1.6.1 | L1 | Ensure core dumps are restricted | Update limits.conf file"
#         lineinfile:
#             state: present
#             dest: /etc/security/limits.conf
#             regexp: '^#?\\*.*core'
#             line: '*                hard    core            0'
#             insertbefore: '^# End of file'

#       - name: "1.6.1 | L1 | PATCH | Ensure core dumps are restricted | Set active kernel parameter"
#         sysctl:
#             name: fs.suid_dumpable
#             value: '0'
#             state: present
#             reload: yes
#             sysctl_set: yes
#             ignoreerrors: yes

#       - name: "1.6.1 | L1 | PATCH | Ensure core dumps are restricted | if systemd coredump"
#         lineinfile:
#             path: /etc/systemd/coredump.conf
#             regexp: "{{ item.regexp }}"
#             line: "{{ item.regexp }}{{ item.line }}"
#             state: present
#         with_items:
#             - {'regexp': 'Storage=', 'line': 'none'}
#             - {'regexp': 'ProcessSizeMax=', 'line': '0'}
#         notify:
#             - systemd_daemon_reload
#         when:
#             - systemd_coredump.stat.exists
#   when:
#       - rhel8cis_rule_1_6_1
#   tags:
#       - level1-server
#       - level1-workstation
#       - scored
#       - sysctl
#       - patch
#       - rule_1.6.1

# - name: "1.6.2 | L1 | PATCH | Ensure address space layout randomization (ASLR) is enabled"
#   sysctl:
#       name: kernel.randomize_va_space
#       value: '2'
#       state: present
#       reload: yes
#       sysctl_set: yes
#       ignoreerrors: yes
#   when:
#       - rhel8cis_rule_1_6_2
#   tags:
#       - level1-server
#       - level1-workstation
#       - scored
#       - patch
#       - rule_1.6.2
