---

- name: "NOTSCORED | 1.2.1 | PATCH | Ensure Red Hat Subscription Manager connection is configured"
  command: subscription-manager register
  changed_when: no
  failed_when: no
  when:
      - ansible_distribution == "RedHat"
      - rhel8cis_rule_1_2_1
  tags:
      - level1-server
      - level1-workstation
      - notscored
      - patch
      - rule_1.2.1

- name: "NOTSCORED | 1.2.2 | PATCH | Disable the rhnsd Daemon"
  service:
      name: rhnsd
      state: stopped
      enabled: no
  when:
      - ansible_distribution == "RedHat" and rhnsd_service_status.stdout == "loaded" and not rhel8cis_rhnsd_required
      - rhel8cis_rule_1_2_2
  tags:
      - level1-server
      - level1-workstation
      - notscored
      - patch
      - rule_1.2.2

- name: "NOTSCORED | 1.2.3 | PATCH | Ensure GPG keys are configured"
  command: gpg --quiet --with-fingerprint /etc/pki/rpm-gpg/RPM-GPG-KEY-{{ ansible_distribution|lower }}-release
  when:
      - rhel8cis_rule_1_2_3
      - ansible_distribution == "RedHat"
  tags:
      - level1-server
      - level1-workstation
      - notscored
      - patch
      - rule_1.2.3

- name: "SCORED | 1.2.4 | PATCH | Ensure gpgcheck is globally activated"
  block:
      - name: "SCORED | 1.2.4 | PATCH | Ensure gpgcheck is globally activated | Find repos"
        find:
            paths: /etc/yum.repos.d
            patterns: "*.repo"
        register: yum_repos
        changed_when: no

      - name: "SCORED | 1.2.4 | PATCH | Ensure gpgcheck is globally activated | Update yum.repos"
        replace:
            name: "{{ item.path }}"
            regexp: "^gpgcheck=0"
            replace: "gpgcheck=1"
        with_items:
            - "{{ yum_repos.files }}"
  when:
      - rhel8cis_rule_1_2_4
  tags:
      - level1-server
      - level1-workstation
      - scored
      - patch
      - rule_1.2.4

- name: "NOTSCORED | 1.2.5 | PATCH | Ensure package manager repositories are configured"
  command: dnf repolist
  args:
      warn: false
  register: dnf_configured
  changed_when: no
  failed_when: no
  when:
      - rhel8cis_rule_1_2_5
  tags:
      - level1-server
      - level1-workstation
      - notscored
      - patch
      - rule_1.2.5
      - skip_ansible_lint