---

- name: "SCORED | 1.1.2 | PATCH | Ensure /tmp is configured| enable and start/restart tmp.mount"
  block:
      - name: "SCORED | 1.1.2 | PATCH | Ensure /tmp is configured | change mount options in config file for systemd"
        lineinfile:
            path: /etc/selinux/config
            regexp: "^Options=mode"
            line: "Options=mode=1777,strictatime,noexec,nodev,nosuid"

      - name: "SCORED | 1.1.2 | PATCH | Ensure /tmp is configured | enforce systemd enabled service"
        systemd:
            name: tmp.mount
            daemon_reload: yes
            enabled: yes
            masked: no
            state: started
  when:
      - rhel8cis_rule_1_1_2
  tags:
      - level1-server
      - level1-workstation
      - scored
      - patch
      - rule_1.1.2

- name: |
        "SCORED | 1.1.3 | PATCH | Ensure nodev option set on /tmp partition"
        "SCORED | 1.1.4 | PATCH | Ensure nosuid option set on /tmp partition"
        "SCORED | 1.1.5 | PATCH | Ensure noexec option set on /tmp partition"
  copy:
      src: etc/systemd/system/tmp.mount
      dest: /etc/systemd/system/tmp.mount
      owner: root
      group: root
      mode: 0644
  notify: systemd restart tmp.mount
  when:
      - rhel8cis_rule_1_1_3
      - rhel8cis_rule_1_1_4
      - rhel8cis_rule_1_1_5
  tags:
      - level1-server
      - level1-workstation
      - scored
      - patch
      - rule_1.1.3
      - rule_1.1.4
      - rule_1.1.5

- name: "SCORED | 1.1.6 | PATCH | Ensure separate partition exists for /var"
  shell: mount | grep "on /var "
  args:
      warn: false
  register: var_mounted
  changed_when: no
  failed_when: no
  when:
      - rhel8cis_rule_1_1_6
  tags:
      - level2-server
      - level2-workstation
      - scored
      - patch
      - rule_1.1.6
      - skip_ansible_lint

- name: "SCORED | 1.1.7 | PATCH | Ensure separate partition exists for /var/tmp"
  shell: mount | grep "on /var/tmp "
  register: var_tmp_mounted
  changed_when: no
  failed_when: no
  when:
      - rhel8cis_rule_1_1_7
  tags:
      - level2-server
      - level2-workstation
      - scored
      - patch
      - rule_1.1.7
      - skip_ansible_lint

- name: |
          "SCORED | 1.1.8  | PATCH | Ensure nodev option set on /var/tmp partition |
           SCORED | 1.1.9  | PATCH | Ensure nosuid option set on /var/tmp partition |
           SCORED | 1.1.10 | PATCH | Ensure noexec option set on /var/tmp partition"
  mount:
      name: /var/tmp
      src: "{{ rhel8cis_vartmp['source'] }}"
      state: present
      fstype: "{{ rhel8cis_vartmp['fstype'] }}"
      opts: "{{ rhel8cis_vartmp['opts'] }}"
  when:
      - rhel8cis_vartmp['enabled']
      - rhel8cis_rule_1_1_8
      - rhel8cis_rule_1_1_9
      - rhel8cis_rule_1_1_10
  tags:
      - level1-server
      - level1-workstation
      - scored
      - patch
      - rule_1.1.8
      - rule_1.1.9
      - rule_1.1.10

- name: "SCORED | 1.1.11 | PATCH | Ensure separate partition exists for /var/log"
  shell: mount | grep "on /var/log "
  register: var_log_mounted
  changed_when: no
  failed_when: no
  when:
      - rhel8cis_rule_1_1_11
  tags:
      - level2-server
      - level2-workstation
      - scored
      - patch
      - rule_1.1.11
      - skip_ansible_lint

- name: "SCORED | 1.1.12 | PATCH | Ensure separate partition exists for /var/log/audit"
  shell: mount | grep "on /var/log/audit "
  register: var_log_audit_mounted
  changed_when: no
  failed_when: no
  when:
      - rhel8cis_rule_1_1_12
  tags:
      - level2-server
      - level2-workstation
      - scored
      - patch
      - rule_1.1.12
      - skip_ansible_lint

- name: "SCORED | 1.1.13 | PATCH | Ensure separate partition exists for /home"
  shell: mount | grep "on /home"
  register: home_mounted
  changed_when: no
  failed_when: no
  when:
      - rhel8cis_rule_1_1_13
  tags:
      - level2-server
      - level2-workstation
      - scored
      - patch
      - rule_1.1.13
      - skip_ansible_lint

- name: "SCORED | 1.1.14 | PATCH | Ensure nodev option set on /home partition"
  mount:
      name: "/home"
      src: "{{ item.device }}"
      state: mounted
      fstype: "{{ item.fstype }}"
      opts: "nodev"
  when:
      - rhel8cis_rule_1_1_14
      - item.mount == "/home"
  with_items: "{{ ansible_mounts }}"
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rule_1.1.14

- name: |
         "SCORED | 1.1.15 | PATCH | Ensure nodev option set on /dev/shm partition |
          SCORED | 1.1.16 | PATCH | Ensure nosuid option set on /dev/shm partition |
          SCORED | 1.1.17 | PATCH | Ensure noexec option set on /dev/shm partition"
  mount:
      name: /dev/shm
      src: tmpfs
      state: mounted
      fstype: tmpfs
      opts: "defaults,nodev,nosuid,noexec"
  when:
      - rhel8cis_rule_1_1_15
      - rhel8cis_rule_1_1_16
      - rhel8cis_rule_1_1_17
  tags:
      - level1-server
      - level1-workstation
      - scored
      - patch
      - rule_1.1.15
      - rule_1.1.16
      - rule_1.1.17

- name: "NOTSCORED | 1.1.18 | PATCH | Ensure nodev option set on removable media partitions"
  debug:
      msg: "--> Not relevant"
  changed_when: no
  when:
      - rhel8cis_rule_1_1_18
  tags:
      - level1-server
      - level1-workstation
      - notscored
      - patch
      - rule_1.1.18

- name: "NOTSCORED | 1.1.19 | PATCH | Ensure nosuid option set on removable media partitions"
  debug:
      msg: "--> Not relevant"
  changed_when: no
  when:
      - rhel8cis_rule_1_1_19
  tags:
      - level1-server
      - level1-workstation
      - notscored
      - patch
      - rule_1.1.19

- name: "NOTSCORED | 1.1.20 | PATCH | Ensure noexec option set on removable media partitions"
  debug:
      msg: "--> Not relevant"
  changed_when: no
  when:
      - rhel8cis_rule_1_1_20
  tags:
      - level1-server
      - level1-workstation
      - notscored
      - patch
      - rule_1.1.20

- name: "SCORED | 1.1.21 | PATCH | Ensure sticky bit is set on all world-writable directories"
  shell: df --local -P | awk {'if (NR!=1) print $6'} | xargs -I '{}' find '{}' -xdev -type d -perm -0002 2>/dev/null | xargs chmod a+t
  changed_when: no
  failed_when: no
  # when: sticky_bit_on_worldwritable_dirs_audit.rc == '0'
  when:
      - rhel8cis_rule_1_1_21
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rule_1.1.21

- name: "SCORED | 1.1.22 | PATCH | Disable Automounting"
  service:
      name: autofs
      enabled: no
  when:
      - not rhel8cis_allow_autofs
      - "'autofs' in ansible_facts.packages"
      - rhel8cis_rule_1_1_22
  tags:
      - level1-server
      - level2-workstation
      - patch
      - rule_1.1.22

- name: "SCORED | 1.1.23 | PATCH | Disable USB Storage"
  block:
      - name: "SCORED | 1.1.23 | PATCH | Disable USB Storage | Edit modprobe config"
        lineinfile:
            dest: /etc/modprobe.d/CIS.conf
            regexp: "^(#)?install usb-storage(\\s|$)"
            line: "install usb-storage /bin/true"
            create: yes
      - name: "SCORED | 1.1.23 | PATCH | Disable USB Storage | Edit modprobe config"
        modprobe:
            name: usb-storage
            state: absent
  when:
      - rhel8cis_rule_1_1_23
  tags:
      - level1-server
      - level2-workstation
      - patch
      - rule_1.1.23