---

- name: "SCORED | 4.1.1.1 | PATCH | Ensure auditd is installed"
  block:
  - name: "SCORED | 4.1.1.1 | PATCH | Ensure auditd is installed | Check for auditd packages"
    command: rpm -q audit audit-libs
    become: true
    failed_when: no
    changed_when: no
    register: rhel8cis_4_1_1_1_auditdpackages

  - name: "SCORED | 4.1.1.1 | PATCH | Ensure auditd is installed | Install auditd packages"
    package:
      name: audit
      state: present
    become: true
    when:
    - '"auditd" not in ansible_facts.packages'

  - name: "SCORED | 4.1.1.1 | PATCH | Ensure auditd is installed | Install auditd-lib packages"
    package:
      name: audit-libs
      state: present
    become: true
    when:
    - '"auditd-lib" not in ansible_facts.packages'
  when:
  - rhel8cis_rule_4_1_1_1
  tags:
  - level2
  - patch
  - rule_4.1.1.1

- name: "SCORED | 4.1.1.2 | PATCH | Ensure auditd service is enabled"
  service:
    name: auditd
    state: started
    enabled: yes
  when:
  - not rhel8cis_skip_for_travis
  - rhel8cis_rule_4_1_1_2
  - ansible_connection != 'docker'
  tags:
  - level2
  - auditd
  - patch
  - rule_4.1.1.2

- name: "SCORED | 4.1.1.3 | PATCH | Ensure auditing for processes that start prior to auditd is enabled"
  replace:
    dest: /etc/default/grub
    regexp: '(^GRUB_CMDLINE_LINUX\s*\=\s*)(?:")(.+)(?<!audit=1)(?:")'
    replace: '\1"\2 audit=1"'
  ignore_errors: yes
  notify: generate new grub config
  when:
  - rhel8cis_rule_4_1_1_3
  tags:
  - level2
  - auditd
  - patch
  - rule_4.1.1.3

- name: "SCORED | 4.1.1.4 | PATCH | Ensure audit_backlog_limit is sufficient"
  replace:
    dest: /etc/default/grub
    regexp: '(^GRUB_CMDLINE_LINUX\s*\=\s*)(?:")(.+)(?<!audit_backlog_limit={{ rhel8cis_audit_back_log_limit }})(?:")'
    replace: '\1"\2 audit_backlog_limit={{ rhel8cis_audit_back_log_limit }}"'
  ignore_errors: yes
  become: true
  when:
  - rhel8cis_rule_4_1_1_4
  tags:
  - level2
  - patch
  - rule_4.1.1.4