---

- name: "4.2.3 | PATCH | Ensure permissions on all logfiles are configured"
  block:
      - name: "4.2.3 | AUDIT | Ensure permissions on all logfiles are configured | find files"
        ansible.builtin.shell: find /var/log/ -type f -perm /g+wx,o+rwx -exec ls {} \;
        changed_when: false
        failed_when: false
        register: rhel8cis_4_2_3_logfiles

      - name: "4.2.3 | AUDIT | Ensure permissions on all logfiles are configured | set_fact"
        ansible.builtin.set_fact:
            rhel8cis_4_2_3_logfiles_flattened: "{{ logfiles.stdout_lines | map(attribute='stdout_lines') | flatten }}"
        when: 
            - rhel8cis_4_2_3_logfiles is defined
            - rhel8cis_4_2_3_logfiles.stdout_lines | length > 0

      - name: "4.2.3 | PATCH | Ensure permissions on all logfiles are configured | change permissions"
        ansible.builtin.file:
            path: "{{ item }}"
            mode: 0640
        loop: "{{ rhel8cis_4_2_3_logfiles_flattened }}"
        when:
            - rhel8cis_4_2_3_logfiles_flattened is defined
            - item != "/var/log/btmp"
            - item != "/var/log/utmp"
            - item != "/var/log/wtmp"
  when:
      - ubtu20cis_rule_4_2_3
  tags:
      - level1-server
      - level1-workstation
      - patch
      - logfiles
      - rule_4.2.3
